/*q1*/
SELECT COUNT(ID) AS number_of_crimes
FROM IBM_Cert.dbo.ChicagoCrimeData$*/

/*q2*/
SELECT COMMUNITY_AREA_NAME, PER_CAPITA_INCOME
FROM IBM_Cert.dbo.ChicagoCensusData_excel$
WHERE PER_CAPITA_INCOME < 11000

/*q3*/
SELECT DISTINCT CASE_NUMBER 
FROM ChicagoCrimeData$
WHERE DESCRIPTION LIKE '%MINOR%'

/*q4*/
SELECT DISTINCT CASE_NUMBER, PRIMARY_TYPE, DATE, DESCRIPTION 
FROM ChicagoCrimeData$
WHERE PRIMARY_TYPE='KIDNAPPING'

/*q5*/
SELECT DISTINCT(PRIMARY_TYPE), LOCATION_DESCRIPTION 
FROM ChicagoCrimeData$
WHERE LOCATION_DESCRIPTION LIKE '%SCHOOL%'

/*q6*/
SELECT "Elementary, Middle, or High School", AVG(SAFETY_SCORE) AVERAGE_SAFETY_SCORE 
FROM ChicagoPublicSchools$
GROUP BY "Elementary, Middle, or High School";

/*q7*/
SELECT top 5 COMMUNITY_AREA_NAME, PERCENT_HOUSEHOLDS_BELOW_POVERTY 
FROM ChicagoCensusData_excel$
ORDER BY PERCENT_HOUSEHOLDS_BELOW_POVERTY DESC;

/*q8*/
SELECT top 1 COMMUNITY_AREA_NUMBER ,COUNT(COMMUNITY_AREA_NUMBER) AS FREQUENCY
FROM ChicagoCrimeData$
GROUP BY COMMUNITY_AREA_NUMBER
ORDER BY COUNT(COMMUNITY_AREA_NUMBER) DESC;

/*q9*/
SELECT COMMUNITY_AREA_NAME 
FROM ChicagoCensusData_excel$ 
WHERE HARDSHIP_INDEX = 
(SELECT MAX(HARDSHIP_INDEX) FROM ChicagoCensusData_excel$);

/*q10*/
SELECT top 1 community_area_name 
FROM ChicagoCensusData_excel$
WHERE COMMUNITY_AREA_NUMBER = (SELECT top 1 COMMUNITY_AREA_NUMBER FROM ChicagoCrimeData$ 
    GROUP BY COMMUNITY_AREA_NUMBER
    ORDER BY COUNT(COMMUNITY_AREA_NUMBER) DESC);